#!/usr/bin/env python3
"""Interactive three-staircase MuJoCo test for a MyBot V3 CSE checkpoint.

Builds one MuJoCo scene containing three parallel staircases and lets the
user drive the robot between them with the keyboard:

    lane 0  y = -2.7 m  (green)   8 cm steps x 10
    lane 1  y =  0.0 m  (orange) 10 cm steps x 10
    lane 2  y = +2.7 m  (red)    12 cm steps x 10

Each staircase starts at x = 0.55 m with 0.30 m treads and a 0.9 m top
platform.  The robot spawns at x = 0 facing +x.

Keyboard:
    W/S      forward / backward        (default 0.4 m/s)
    A/D      lateral left / right      (default 0.3 m/s)
    Q/E      yaw left / right          (default 0.8 rad/s)
    1/2/3    teleport to the start of lane 0/1/2
    R        teleport back to the origin
    arrows   push the base horizontally (disturbance force)
    U/O      push the base up / down

This test intentionally keeps the last known-good MuJoCo baseline isolated
from the aligned deployment model: damping/friction and collision geometry
come from ``mybot_v3.xml.bak_matched``, action targets have no extra fixed lag,
and joint-position targets are clipped to the model limits.  Default weights
are checkpoint 59950.

Headless smoke test:
    python scripts/sim2sim_mujoco_3stairs.py --headless --vx 0.3 --duration 3
"""

import argparse
import re
import sys
import time
from pathlib import Path

import mujoco
import mujoco.viewer
import numpy as np

SCRIPTS_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPTS_DIR.parent
sys.path.insert(0, str(SCRIPTS_DIR))

from sim2sim_mujoco import (  # noqa: E402
    KeyboardController,
    MybotV3Sim,
    apply_policy_profile,
    load_config,
)

DEFAULT_CONFIG = PROJECT_ROOT / "deploy_cpp/config/robots/mybot_v3_cse_sim.yaml"
CKPT_DIR = (
    PROJECT_ROOT
    / "runs/mybot_v3_sim2sim_phase3b_resume_059500/2026-10-03_07-04-56.647780/checkpoints"
)
DEFAULT_BODY = CKPT_DIR / "body_059950.jit"
DEFAULT_ADAPTATION = CKPT_DIR / "adaptation_module_059950.jit"
SCENE_CACHE = PROJECT_ROOT / "tmp/mujoco_3stairs/mybot_v3_3stairs.xml"
BASELINE_XML = (
    PROJECT_ROOT / "deploy_cpp/robot/mybot_v3/xml/mybot_v3.xml.bak_matched"
)
ALIGNED_XML = PROJECT_ROOT / "deploy_cpp/robot/mybot_v3/xml/mybot_v3.xml"

# (y center, step height [m], rgba)
LANES = (
    (-2.7, 0.08, "0.20 0.65 0.30 1"),
    (0.0, 0.10, "0.90 0.55 0.10 1"),
    (2.7, 0.12, "0.80 0.20 0.20 1"),
)
LANE_LABELS = ("8cm", "10cm", "12cm")
NUM_STEPS = 10
TREAD_DEPTH = 0.30
WIDTH = 2.0
X_START = 0.55
TOP_LENGTH = 0.90
FRICTION = "1 0.005 0.0001"
SPAWN_HEIGHT = 0.35


def build_scene_xml(base_text: str, xml_path: Path) -> str:
    """Strip the built-in single staircase and inject three stair lanes."""
    text, removed = re.subn(
        r'^\s*<geom name="sim_(?:stair|three_stair)_[^"]*"[^>]*/>\s*\n',
        "",
        base_text,
        flags=re.M,
    )
    if removed < 9:
        raise RuntimeError(
            f"expected >=9 sim_stair placeholder geoms in robot XML, removed {removed}"
        )

    # The cache file lives outside the robot package, so make the relative
    # mesh directory absolute.
    mesh_dir = (xml_path.parent / "../meshes").resolve()
    text, subs = re.subn(
        r'meshdir="[^"]*"', f'meshdir="{mesh_dir}"', text, count=1
    )
    if subs != 1:
        raise RuntimeError("meshdir attribute not found in robot XML")

    geoms = []
    for lane, (y, height, rgba) in enumerate(LANES):
        for index in range(NUM_STEPS):
            top_z = (index + 1) * height
            x = X_START + (index + 0.5) * TREAD_DEPTH
            geoms.append(
                f'        <geom name="t{lane}step{index}" type="box" '
                f'pos="{x:.3f} {y:.3f} {0.5 * top_z:.4f}" '
                f'size="{0.5 * TREAD_DEPTH:.3f} {0.5 * WIDTH:.3f} {0.5 * top_z:.4f}" '
                f'contype="1" conaffinity="1" friction="{FRICTION}" rgba="{rgba}" />'
            )
        top_z = NUM_STEPS * height
        x = X_START + NUM_STEPS * TREAD_DEPTH + 0.5 * TOP_LENGTH
        geoms.append(
            f'        <geom name="t{lane}top" type="box" '
            f'pos="{x:.3f} {y:.3f} {0.5 * top_z:.4f}" '
            f'size="{0.5 * TOP_LENGTH:.3f} {0.5 * WIDTH:.3f} {0.5 * top_z:.4f}" '
            f'contype="1" conaffinity="1" friction="{FRICTION}" rgba="{rgba}" />'
        )

    anchor = '<geom name="floor"'
    insert_at = text.index("\n", text.index(anchor)) + 1
    header = (
        "        <!-- three-staircase interactive test scene "
        "(generated by sim2sim_mujoco_3stairs.py) -->\n"
    )
    return text[:insert_at] + header + "\n".join(geoms) + "\n" + text[insert_at:]


class ThreeStairsSim(MybotV3Sim):
    """MybotV3Sim with a three-lane staircase terrain instead of one staircase."""

    def __init__(self, config, body_path, adaptation_path, package_root, profile):
        self.profile = profile
        xml_path = BASELINE_XML if profile == "baseline" else ALIGNED_XML
        if not xml_path.is_file():
            raise RuntimeError(f"MuJoCo source XML is missing: {xml_path}")
        scene_text = build_scene_xml(xml_path.read_text(), xml_path)
        SCENE_CACHE.parent.mkdir(parents=True, exist_ok=True)
        SCENE_CACHE.write_text(scene_text)
        config = dict(config)
        # Reproduce the controller used by the successful interactive test.
        # Phase3B randomized lag during training, but the known-good MuJoCo
        # baseline did not inject an additional deterministic delay.
        config["action_lag_steps"] = 0
        config["mujoco_xml_relpath"] = str(SCENE_CACHE)
        super().__init__(config, body_path, adaptation_path, "stairs", package_root)
        if profile not in ("baseline", "dynamics"):
            self._configure_single_variable_profile(profile)

    def _configure_single_variable_profile(self, profile):
        """Change one passive term while retaining aligned collision shapes."""
        for joint_index, dof_index in enumerate(self.joint_qvel_idx):
            kind = joint_index % 3
            baseline_damping = 1.0 if kind == 0 else 2.0
            baseline_armature = 0.0544 if kind == 2 else 0.01
            aligned_frictionloss = 0.3 if kind == 2 else 0.1
            self.model.dof_damping[dof_index] = (
                0.0 if profile == "damping" else baseline_damping
            )
            self.model.dof_frictionloss[dof_index] = (
                aligned_frictionloss
                if profile in ("friction", "aligned_damped")
                else 0.2
            )
            self.model.dof_armature[dof_index] = (
                0.01
                if profile in ("armature", "aligned_damped")
                else baseline_armature
            )

        # Restore the old robot-surface friction while retaining the aligned
        # body/hip/calf collision sizes and self-collision filter.
        if profile != "aligned_damped":
            for geom_id in range(self.model.ngeom):
                if (
                    self.model.geom_bodyid[geom_id] != 0
                    and self.model.geom_contype[geom_id]
                ):
                    self.model.geom_friction[geom_id] = (0.6, 0.3, 0.3)

    def _configure_terrain(self):
        active_ids = []
        for lane, (y, height, rgba) in enumerate(LANES):
            for index in range(NUM_STEPS):
                geom_id = mujoco.mj_name2id(
                    self.model, mujoco.mjtObj.mjOBJ_GEOM, f"t{lane}step{index}"
                )
                if geom_id < 0:
                    raise RuntimeError(f"scene geom missing: t{lane}step{index}")
                top_z = (index + 1) * height
                self.model.geom_contype[geom_id] = 1
                self.model.geom_conaffinity[geom_id] = 1
                self.model.geom_pos[geom_id] = (
                    X_START + (index + 0.5) * TREAD_DEPTH,
                    y,
                    0.5 * top_z,
                )
                self.model.geom_size[geom_id] = (
                    0.5 * TREAD_DEPTH,
                    0.5 * WIDTH,
                    0.5 * top_z,
                )
                active_ids.append(int(geom_id))
            top_id = mujoco.mj_name2id(
                self.model, mujoco.mjtObj.mjOBJ_GEOM, f"t{lane}top"
            )
            if top_id < 0:
                raise RuntimeError(f"scene geom missing: t{lane}top")
            top_z = NUM_STEPS * height
            self.model.geom_contype[top_id] = 1
            self.model.geom_conaffinity[top_id] = 1
            self.model.geom_pos[top_id] = (
                X_START + NUM_STEPS * TREAD_DEPTH + 0.5 * TOP_LENGTH,
                y,
                0.5 * top_z,
            )
            self.model.geom_size[top_id] = (
                0.5 * TOP_LENGTH,
                0.5 * WIDTH,
                0.5 * top_z,
            )
            active_ids.append(int(top_id))
        return active_ids

    def height_distances(self) -> np.ndarray:
        """Use the height query from the last known-good MuJoCo test."""
        base_x, base_y, base_z = self.data.qpos[:3]
        w, x, y, z = self.data.qpos[3:7]
        yaw = np.arctan2(2.0 * (w * z + x * y), 1.0 - 2.0 * (y * y + z * z))
        cy, sy = np.cos(yaw), np.sin(yaw)
        grid_x, grid_y = np.meshgrid(self.height_x, self.height_y, indexing="ij")
        world_x = base_x + cy * grid_x - sy * grid_y
        world_y = base_y + sy * grid_x + cy * grid_y

        ground_z = np.zeros_like(world_x, dtype=np.float32)
        for geom_id in self.stair_geom_ids:
            center = self.model.geom_pos[geom_id]
            half_size = self.model.geom_size[geom_id]
            inside = (
                (np.abs(world_x - center[0]) <= half_size[0])
                & (np.abs(world_y - center[1]) <= half_size[1])
            )
            top_z = np.float32(center[2] + half_size[2])
            ground_z = np.where(inside, np.maximum(ground_z, top_z), ground_z)
        return (base_z - ground_z).astype(np.float32).reshape(-1)

    def teleport(self, x: float, y: float, yaw: float = 0.0):
        """Reset the robot to a clean standing pose at the given position."""
        qpos = np.asarray(self.data.qpos).copy()
        qpos[0:3] = (x, y, SPAWN_HEIGHT)
        half = 0.5 * yaw
        qpos[3:7] = (np.cos(half), 0.0, 0.0, np.sin(half))  # w x y z
        self.data.qpos[:] = qpos
        self.data.qvel[:] = 0.0
        for index, qpos_index in enumerate(self.joint_qpos_idx):
            self.data.qpos[qpos_index] = self.policy_dof_pos[index]
        self.data.ctrl[:] = 0.0
        mujoco.mj_forward(self.model, self.data)
        self.policy_history.zero_()
        self.estimator_history.zero_()
        self.last_actions.zero_()
        self.action_lag_buffer = [
            np.zeros(12, dtype=np.float32)
            for _ in range(self.action_lag_steps + 1)
        ]
        self.initial_base = np.asarray(self.data.qpos[:3], dtype=np.float32).copy()
        self.min_base_z = float(self.data.qpos[2])
        self.max_base_z = float(self.data.qpos[2])
        self.max_tilt_rad = 0.0
        self.fell = False

    def lane_at(self) -> str:
        y = float(self.data.qpos[1])
        lane = int(np.argmin([abs(y - entry[0]) for entry in LANES]))
        return f"{lane}:{LANE_LABELS[lane]}"


class TestKeyboardController(KeyboardController):
    """Parent keyboard map plus 1/2/3 teleport and R reset."""

    EXTRA_KEYS = ("1", "2", "3", "r")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.keys.update({name: False for name in self.EXTRA_KEYS})

    def consume(self, name: str) -> bool:
        if self.keys.get(name):
            self.keys[name] = False
            return True
        return False


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--body", type=Path, default=DEFAULT_BODY)
    parser.add_argument("--adaptation", type=Path, default=DEFAULT_ADAPTATION)
    parser.add_argument("--vx", type=float, default=0.4)
    parser.add_argument("--vy", type=float, default=0.3)
    parser.add_argument("--yaw", type=float, default=0.8)
    parser.add_argument("--disturbance-force", type=float, default=None)
    parser.add_argument("--headless", action="store_true")
    parser.add_argument("--duration", type=float, default=10.0)
    parser.add_argument(
        "--profile",
        choices=(
            "baseline",
            "collision",
            "armature",
            "damping",
            "friction",
            "aligned_damped",
            "dynamics",
        ),
        default="collision",
        help=(
            "baseline; collision-only; one passive term; or all aligned dynamics"
        ),
    )
    args = parser.parse_args()

    config_path = args.config.expanduser().resolve()
    config = load_config(config_path)
    apply_policy_profile(config, "config")
    package_root = config_path.parents[2]

    sim = ThreeStairsSim(
        config,
        args.body.expanduser().resolve(),
        args.adaptation.expanduser().resolve(),
        package_root,
        args.profile,
    )
    action_scale = float(config["action_scale"])
    print(f"[3stairs] scene={SCENE_CACHE}")
    print(
        "[3stairs] lanes (y center): "
        + ", ".join(
            f"{label}@y={entry[0]:+.1f}m/{entry[1]*100:.0f}cm"
            for entry, label in zip(LANES, LANE_LABELS)
        )
    )
    print(
        f"[3stairs] stairs start x={X_START}m, {NUM_STEPS} steps, "
        f"tread={TREAD_DEPTH}m, top={TOP_LENGTH}m"
    )
    print(
        f"[3stairs] profile={args.profile} checkpoint=059950 "
        "action_lag_steps=0 target_clip=joint_limits external_force_default=0N "
        "zero_command=stand_hold(kp_x2,kd_x2,gravity_preload)"
    )

    command_deadband = float(config["cmd_deadband"])
    stand_blend = 0.12
    motion_kp = sim.kp.copy()
    motion_kd = sim.kd.copy()
    stand_kp = 2.0 * motion_kp
    stand_kd = 2.0 * motion_kd
    # Preload the static pose against gravity.  These small offsets were
    # measured in the aligned_damped MuJoCo model so that the loaded joints
    # settle close to policy_dof_pos instead of sagging into a crouch.
    stand_target = np.clip(
        sim.policy_dof_pos
        + np.array(
            [
                -0.05, 0.02, 0.10,
                +0.05, 0.02, 0.10,
                -0.08, 0.02, 0.11,
                +0.08, 0.02, 0.11,
            ],
            dtype=np.float32,
        ),
        sim.lower,
        sim.upper,
    )
    last_target = sim.policy_dof_pos.copy()
    was_moving = False

    def reset_policy_memory():
        sim.policy_history.zero_()
        sim.estimator_history.zero_()
        sim.last_actions.zero_()
        sim.action_lag_buffer = [
            np.zeros(12, dtype=np.float32)
            for _ in range(sim.action_lag_steps + 1)
        ]

    def reset_control_state():
        nonlocal last_target, was_moving
        reset_policy_memory()
        last_target = sim.policy_dof_pos.copy()
        was_moving = False

    def apply_action(command, disturbance):
        nonlocal last_target, was_moving
        moving = bool(np.linalg.norm(command) >= command_deadband)
        if moving:
            sim.kp[:] = motion_kp
            sim.kd[:] = motion_kd
            if not was_moving:
                reset_policy_memory()
            action = sim.infer(command)
            last_target = np.clip(
                sim.policy_dof_pos + action * action_scale,
                sim.lower,
                sim.upper,
            )
        else:
            sim.kp[:] = stand_kp
            sim.kd[:] = stand_kd
            if was_moving:
                reset_policy_memory()
            action = np.zeros(12, dtype=np.float32)
            last_target = (
                last_target
                + stand_blend * (stand_target - last_target)
            )
        was_moving = moving
        sim.step_control(last_target, disturbance)
        return action

    if args.headless:
        command = np.array([args.vx, args.vy, 0.0], dtype=np.float32)
        steps = max(1, int(args.duration / sim.control_dt))
        for step in range(steps):
            apply_action(command, None)
            if step % 25 == 0:
                base = sim.data.qpos[:3]
                print(
                    f"[3stairs] step={step} lane={sim.lane_at()} base="
                    f"[{base[0]:.2f}, {base[1]:.2f}, {base[2]:.2f}]"
                )
        print(f"[3stairs] summary={sim.summary()}")
        return

    disturbance_force_n = (
        float(config.get("external_force_n", 35.0))
        if args.disturbance_force is None
        else float(args.disturbance_force)
    )
    try:
        controller = TestKeyboardController(
            disturbance_force_n, args.vx, args.vy, args.yaw
        )
    except Exception as exc:  # pragma: no cover - depends on desktop session
        raise RuntimeError(
            "interactive mode requires a desktop keyboard listener (pynput)"
        ) from exc

    print("[3stairs] keyboard: W/S forward, A/D lateral, Q/E yaw, "
          "1/2/3 teleport to lane, R reset, arrows push, U/O vertical push")
    fell_announced = False
    with mujoco.viewer.launch_passive(sim.model, sim.data) as viewer:
        viewer.cam.lookat[:] = (2.6, 0.0, 0.6)
        viewer.cam.distance = 9.5
        viewer.cam.elevation = -22.0
        viewer.cam.azimuth = 135.0
        step = 0
        while viewer.is_running():
            start = time.time()
            if controller.consume("r"):
                sim.teleport(0.0, 0.0)
                reset_control_state()
                fell_announced = False
                print("[3stairs] reset to origin")
            for key, y_pos in zip(("1", "2", "3"), (LANES[0][0], LANES[1][0], LANES[2][0])):
                if controller.consume(key):
                    sim.teleport(0.0, y_pos)
                    reset_control_state()
                    fell_announced = False
                    print(f"[3stairs] teleport to lane {key} (y={y_pos:+.1f})")
            action = apply_action(controller.command(), controller.disturbance())
            step += 1
            if sim.fell and not fell_announced:
                fell_announced = True
                print("[3stairs] fall detected - press R or 1/2/3 to reset")
            if step % 50 == 0:
                base = sim.data.qpos[:3]
                print(
                    f"[3stairs] step={step} lane={sim.lane_at()} base="
                    f"[{base[0]:.2f}, {base[1]:.2f}, {base[2]:.2f}] "
                    f"action=[{action.min():.2f}, {action.max():.2f}]"
                )
            viewer.sync()
            remaining = sim.control_dt - (time.time() - start)
            if remaining > 0:
                time.sleep(remaining)
    controller.close()
    print(f"[3stairs] summary={sim.summary()}")


if __name__ == "__main__":
    main()
